#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --experimental-backends --backend glx --xrender-sync-fence --config ~/.config/picom/picom.conf &
pgrep -x fcitx5 > /dev/null || fcitx5 &
pgrep -x parcellite > /dev/null || parcellite &
nitrogen --restore &

$HOME/.config/polybar/launch.sh
#bspc monitor DP-0 I II III IV V VI VII VIII IX X
bspc monitor DP-0 -s HDMI-0
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8
bspc monitor HDMI-0 -d 9 10

bspc config border_width	4
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config normal_border_color		"#434c5e"
bspc config focused_border_color	"#81A1C1"
bspc config urgent_border_color		"#88C0D0"
bspc config presel_border_color		"#8FBCBB"
bspc config presel_feedback_color	"#B48EAD"

bspc rule -a Gimp-2.10 desktop='4' state=floating follow=on
bspc rule -a mpv desktop='10' follow=on
bspc rule -a Thunar state=floating rectangle=1200x800+680+320
bspc rule -a Pcmanfm state=floating
bspc rule -a Peek state=floating
bspc rule -a Alacritty state=floating
bspc rule -a Sxiv state=floating
bspc rule -a vlc state=floating

#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
